### ISSUE TITLE
Flow example - implicit flow

### ISSUE THREAD

**Issue by zarkoc** [zitadel/oidc#135]
Hi all,

Im trying to implement a client using the Implicit flow.
But the question is also more general, I cant find how and where to set up the response_type so that I can change the flow to implicit.

To me its seems that the default flow is the authorization_code flow.

Thanks,
Zarko

**Comment by Azmisov** [comment]
I'm looking at Facebook's OIDC support here: https://www.facebook.com/.well-known/openid-configuration... their so called "limited login". Appears to only support the implicit `id_token` response type however.

@livio-a When you say "there is no need to support it [the implicit flow]", are you implying there is another way to handle auth to a service like Facebook OIDC from our end? If so, what would you recommend? Or were you implying that a provider not supporting the `code` response_type would never occur in practice?

**Comment by muhlemmer** [comment]
Implicit only makes sense in certain Single Page Apps running in browsers, where the app can't or won't call the token endpoint using the `code` in the redirect URL. As this is a Go library, the client always runs in a server context and it is always possible to call the token endpoint. Implicit is also considered less secure as code flow. Hence, we did not see the need. 

If there are mayor vendors that only support implicit, we might reconsider based on popular demand of the zitadel and /or oidc community. Technically speaking one should write to Facebook and kindly ask them to support code flow instead, given the above reasoning that seems to be more sane.
