### ISSUE TITLE
Multiple issuer support

### ISSUE THREAD

**Issue by livio-a** [zitadel/oidc#146]
The library should be able to handle multiple issuers on a single OpenID Provider.

**Acceptance Criteria**

- [ ] whenever possible changes are done without breaking current interfaces / implementations of this library
- [ ] issuer can be selected based on http request / context
- [ ] default implementation of the OP interface supports single and multi mode

**Comment by hifabienne** [comment]
I think this is already done right? Can we close it @livio-a

**Comment by muhlemmer** [comment]
I will close, as it is merged in the `next` branch. (This is the temporary target for all breaking changes)
