### ISSUE TITLE
Example for api instrospection

### ISSUE THREAD

**Issue by iambudi** [zitadel/oidc#206]
In the `example/client/api` i always get 401 from token instrospection when calling /protected.
```go
resp, err := rs.Introspect(r.Context(), provider, token)
if err != nil {
	http.Error(w, err.Error(), http.StatusForbidden)
	return
}
```
The step: 
1. Get an access token from `example/client/service`
2. Pass the token as Authorization Bearer to /protected.

Did i miss something?

**Comment by livio-a** [comment]
Hey @iambudi 

The introspection endpoint is a protected endpoint of the Authorization Server itself.
Therefore the API will need to authenticate. In the example it does so with the [JWT Profile](https://www.rfc-editor.org/rfc/rfc7523.html). See also our docs in ZITADEL: https://docs.zitadel.com/docs/apis/openidoauth/endpoints#introspection_endpoint
<img width="993" alt="image" src="https://user-images.githubusercontent.com/9405495/185848261-3cd3a0b6-65b9-4916-9823-c283a6e74961.png">

You will need to provide a key to the example:
```
func main() {
	keyPath := os.Getenv("KEY")
	port := os.Getenv("PORT")
	issuer := os.Getenv("ISSUER")

	provider, err := rs.NewResourceServerFromKeyFile(issuer, keyPath)
```
If your Authorization Server / OpenID Provider does not support this authentication method on the introspection endpoint, you could change the example to use Basic Auth using the `rs.NewResourceServerClientCredentials`

**Comment by hifabienne** [comment]
We will close this issue, since it is resolved from our perspective.
Please feel free to reopen if something is missing

**Comment by muhlemmer** [comment]
You should use a JWT issued for the client for client authentication, not service user.

1. Select a project
2. Add "New" application

![image](https://user-images.githubusercontent.com/5411563/227938309-8e94911b-ccaa-44db-aa1d-8fc6437a665c.png)

3. Under type off application select "API"

![image](https://user-images.githubusercontent.com/5411563/227938479-98b92e14-81b9-40f9-940e-086ee6d38a08.png)

4. Select Authentication method JWT

![image](https://user-images.githubusercontent.com/5411563/227938630-9f6e6799-e582-4995-9532-bcddbbf1a3c0.png)

5. After the app is created, you can add and download keys.

![image](https://user-images.githubusercontent.com/5411563/227938891-aedf9e67-2f0d-412f-bf7c-a95ec093c910.png)

```
{"type":"application","keyId":"207069897346253057","key":"-----BEGIN RSA PRIVATE KEY-----xxxx-----END RSA PRIVATE KEY-----\n","appId":"207069806615068929","clientId":"207069806615134465@test1"}
```

6. Use the **application** JWT in `KEY=` variable in the `go run api.go` command

```
KEY="/home/timz/Downloads/207069897346253057.json" PORT="9099" ISSUER="https://tims-zitadel-instance-oj7iry.zitadel.cloud" go run example/client/api/api.go
2023/03/27 15:19:50 listening on http://127.0.0.1:9099/
```

7. For the service user, create a "personal access token" and set it in the curl header.

![image](https://user-images.githubusercontent.com/5411563/227940321-4a25cba3-e91b-46b5-9889-9290c11bd4e5.png)

```
curl localhost:9099/protected --header "Authorization: Bearer RznbuQZBQVH2ySfe2zbQh6iSYTF-esvbRS0ad1pTErxTngxPUyh_A7GQma6NuOhGJlsmjnA"
{"active":true,"aud":["207069806615134465@test1"],"exp":1680037200,"iat":1679919769,"iss":"https://tims-zitadel-instance-oj7iry.zitadel.cloud","jti":"207070723204710657","nbf":1679919769,"scope":"openid urn:zitadel:iam:user:metadata urn:zitadel:iam:user:resourceowner","sub":"207068608000426241","token_type":"Bearer","urn:zitadel:iam:user:resourceowner:id":"207065153319993601","urn:zitadel:iam:user:resourceowner:name":"TimsZitadelInstance","urn:zitadel:iam:user:resourceowner:primary_domain":"timszitadelinstance.zitadel.cloud"}
```

If you have any other questions, please reach out over [discord](https://discord.gg/erh5Brh7jE) or github [discussions](https://github.com/zitadel/zitadel/discussions/categories/q-a) for the zitadel product.

**Comment by muhlemmer** [comment]
You should use a JWT issued for the client for client authentication, not service user.

1. Select a project
2. Add "New" application

![image](https://user-images.githubusercontent.com/5411563/227938309-8e94911b-ccaa-44db-aa1d-8fc6437a665c.png)

3. Under type off application select "API"

![image](https://user-images.githubusercontent.com/5411563/227938479-98b92e14-81b9-40f9-940e-086ee6d38a08.png)

4. Select Authentication method JWT

![image](https://user-images.githubusercontent.com/5411563/227938630-9f6e6799-e582-4995-9532-bcddbbf1a3c0.png)

5. After the app is created, you can add and download keys.

![image](https://user-images.githubusercontent.com/5411563/227938891-aedf9e67-2f0d-412f-bf7c-a95ec093c910.png)

```
{"type":"application","keyId":"207069897346253057","key":"-----BEGIN RSA PRIVATE KEY-----xxxx-----END RSA PRIVATE KEY-----\n","appId":"207069806615068929","clientId":"207069806615134465@test1"}
```

6. Use the **application** JWT in `KEY=` variable in the `go run api.go` command

```
KEY="/home/timz/Downloads/207069897346253057.json" PORT="9099" ISSUER="https://tims-zitadel-instance-oj7iry.zitadel.cloud" go run example/client/api/api.go
2023/03/27 15:19:50 listening on http://127.0.0.1:9099/
```

7. For the service user, create a "personal access token" and set it in the curl header.

![image](https://user-images.githubusercontent.com/5411563/227940321-4a25cba3-e91b-46b5-9889-9290c11bd4e5.png)

```
curl localhost:9099/protected --header "Authorization: Bearer RznbuQZBQVH2ySfe2zbQh6iSYTF-esvbRS0ad1pTErxTngxPUyh_A7GQma6NuOhGJlsmjnA"
{"active":true,"aud":["207069806615134465@test1"],"exp":1680037200,"iat":1679919769,"iss":"https://tims-zitadel-instance-oj7iry.zitadel.cloud","jti":"207070723204710657","nbf":1679919769,"scope":"openid urn:zitadel:iam:user:metadata urn:zitadel:iam:user:resourceowner","sub":"207068608000426241","token_type":"Bearer","urn:zitadel:iam:user:resourceowner:id":"207065153319993601","urn:zitadel:iam:user:resourceowner:name":"TimsZitadelInstance","urn:zitadel:iam:user:resourceowner:primary_domain":"timszitadelinstance.zitadel.cloud"}
```

If you have any other questions, please reach out over [discord](https://discord.gg/erh5Brh7jE) or github [discussions](https://github.com/zitadel/zitadel/discussions/categories/q-a) for the zitadel product.

**Comment by muhlemmer** [comment]
You should use a JWT issued for the client for client authentication, not service user.

1. Select a project
2. Add "New" application

![image](https://user-images.githubusercontent.com/5411563/227938309-8e94911b-ccaa-44db-aa1d-8fc6437a665c.png)

3. Under type off application select "API"

![image](https://user-images.githubusercontent.com/5411563/227938479-98b92e14-81b9-40f9-940e-086ee6d38a08.png)

4. Select Authentication method JWT

![image](https://user-images.githubusercontent.com/5411563/227938630-9f6e6799-e582-4995-9532-bcddbbf1a3c0.png)

5. After the app is created, you can add and download keys.

![image](https://user-images.githubusercontent.com/5411563/227938891-aedf9e67-2f0d-412f-bf7c-a95ec093c910.png)

```
{"type":"application","keyId":"207069897346253057","key":"-----BEGIN RSA PRIVATE KEY-----xxxx-----END RSA PRIVATE KEY-----\n","appId":"207069806615068929","clientId":"207069806615134465@test1"}
```

6. Use the **application** JWT in `KEY=` variable in the `go run api.go` command

```
KEY="/home/timz/Downloads/207069897346253057.json" PORT="9099" ISSUER="https://tims-zitadel-instance-oj7iry.zitadel.cloud" go run example/client/api/api.go
2023/03/27 15:19:50 listening on http://127.0.0.1:9099/
```

7. For the service user, create a "personal access token" and set it in the curl header.

![image](https://user-images.githubusercontent.com/5411563/227940321-4a25cba3-e91b-46b5-9889-9290c11bd4e5.png)

```
curl localhost:9099/protected --header "Authorization: Bearer RznbuQZBQVH2ySfe2zbQh6iSYTF-esvbRS0ad1pTErxTngxPUyh_A7GQma6NuOhGJlsmjnA"
{"active":true,"aud":["207069806615134465@test1"],"exp":1680037200,"iat":1679919769,"iss":"https://tims-zitadel-instance-oj7iry.zitadel.cloud","jti":"207070723204710657","nbf":1679919769,"scope":"openid urn:zitadel:iam:user:metadata urn:zitadel:iam:user:resourceowner","sub":"207068608000426241","token_type":"Bearer","urn:zitadel:iam:user:resourceowner:id":"207065153319993601","urn:zitadel:iam:user:resourceowner:name":"TimsZitadelInstance","urn:zitadel:iam:user:resourceowner:primary_domain":"timszitadelinstance.zitadel.cloud"}
```

If you have any other questions, please reach out over [discord](https://discord.gg/erh5Brh7jE) or github [discussions](https://github.com/zitadel/zitadel/discussions/categories/q-a) for the zitadel product.

**Comment by muhlemmer** [comment]
You should use a JWT issued for the client for client authentication, not service user.

1. Select a project
2. Add "New" application

![image](https://user-images.githubusercontent.com/5411563/227938309-8e94911b-ccaa-44db-aa1d-8fc6437a665c.png)

3. Under type off application select "API"

![image](https://user-images.githubusercontent.com/5411563/227938479-98b92e14-81b9-40f9-940e-086ee6d38a08.png)

4. Select Authentication method JWT

![image](https://user-images.githubusercontent.com/5411563/227938630-9f6e6799-e582-4995-9532-bcddbbf1a3c0.png)

5. After the app is created, you can add and download keys.

![image](https://user-images.githubusercontent.com/5411563/227938891-aedf9e67-2f0d-412f-bf7c-a95ec093c910.png)

```
{"type":"application","keyId":"207069897346253057","key":"-----BEGIN RSA PRIVATE KEY-----xxxx-----END RSA PRIVATE KEY-----\n","appId":"207069806615068929","clientId":"207069806615134465@test1"}
```

6. Use the **application** JWT in `KEY=` variable in the `go run api.go` command

```
KEY="/home/timz/Downloads/207069897346253057.json" PORT="9099" ISSUER="https://tims-zitadel-instance-oj7iry.zitadel.cloud" go run example/client/api/api.go
2023/03/27 15:19:50 listening on http://127.0.0.1:9099/
```

7. For the service user, create a "personal access token" and set it in the curl header.

![image](https://user-images.githubusercontent.com/5411563/227940321-4a25cba3-e91b-46b5-9889-9290c11bd4e5.png)

```
curl localhost:9099/protected --header "Authorization: Bearer RznbuQZBQVH2ySfe2zbQh6iSYTF-esvbRS0ad1pTErxTngxPUyh_A7GQma6NuOhGJlsmjnA"
{"active":true,"aud":["207069806615134465@test1"],"exp":1680037200,"iat":1679919769,"iss":"https://tims-zitadel-instance-oj7iry.zitadel.cloud","jti":"207070723204710657","nbf":1679919769,"scope":"openid urn:zitadel:iam:user:metadata urn:zitadel:iam:user:resourceowner","sub":"207068608000426241","token_type":"Bearer","urn:zitadel:iam:user:resourceowner:id":"207065153319993601","urn:zitadel:iam:user:resourceowner:name":"TimsZitadelInstance","urn:zitadel:iam:user:resourceowner:primary_domain":"timszitadelinstance.zitadel.cloud"}
```

If you have any other questions, please reach out over [discord](https://discord.gg/erh5Brh7jE) or github [discussions](https://github.com/zitadel/zitadel/discussions/categories/q-a) for the zitadel product.

**Comment by fabius** [comment]
Thanks, that works! I think the wording in docs is a bit misleading here. At the moment, it states that you should create an api and **download the key for the service user** https://zitadel.com/docs/examples/secure-api/go#prerequisites

**Comment by muhlemmer** [comment]
I've posted an issue on zitadel for follow up :point_up:
