### ISSUE TITLE
No method to get all all claims

### ISSUE THREAD

**Issue by morigs** [zitadel/oidc#208]
**Is your feature request related to a problem? Please describe.**
In our service we need to get all claims. Currently, UserInfo allows getting only known claims by name.

**Describe the solution you'd like**
Just additional method `GetClaims() map[string]any` in `UserInfo` interface

**Comment by morigs** [comment]
@livio-a this is a critical feature to us, could you pls help with review of the PR? Do we need to provide any info/help?

**Comment by fforootd** [comment]
Hi @morigs we have our planning meeting today afternoon and will come back with an ETA after that.

**Comment by livio-a** [comment]
I'll approve the PR in a sec to solve the immediate need until we have a proper solution like requested here: https://github.com/zitadel/oidc/issues/182
