### ISSUE TITLE
Missing Copyright notice

### ISSUE THREAD

**Issue by maxdebayser** [zitadel/oidc#214]
As of revision fca6cf94339eacb7db9b4f5fc5c9b8e66781c495, the LICENSE file has an [incomplete copyright notice](https://github.com/zitadel/oidc/blob/fca6cf94339eacb7db9b4f5fc5c9b8e66781c495/LICENSE#L189):

```
Copyright [yyyy] [name of copyright owner]
```

I've developed derivative work based on the `example/server` code and I need to know the correct copyright holder to give credit and comply with the Apache License.

By the way, thanks a lot for making all this work available under an open-source license.

**Comment by maxdebayser** [comment]
This article has some nice suggestions, such as "Copyright The XYZ Contributors."

https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects

**Comment by fforootd** [comment]
Hm I think we had such a discussion in the past in an other project.

The mentioned part is only intended to be used as [template checkout this](https://github.com/zitadel/oidc/blob/main/LICENSE#L178) 

I think we should apply a CLA if we need to fix this for good. Or do you interpret that in an other way?

**Comment by maxdebayser** [comment]
Yes, exactly, I would like to add the template part of the license to derivative work and I need something to insert in place of "[name of copyright owner]" to give due credit to the authors of this library.

**Comment by maxdebayser** [comment]
And yes, you're right. It's not the LICENSE file that should have the copyright, but the NOTICE file. However there is no notice file in the zitadel/oidc repository.

**Comment by maxdebayser** [comment]
Thanks a lot. I've found the PR, it's exactly what I had in mind.
