### ISSUE TITLE
How to set prompt on authorize request

### ISSUE THREAD

**Issue by shnplr** [zitadel/oidc#241]
**Is your feature request related to a problem? Please describe.**
Trying to set a prompt value in authorization request

**Describe the solution you'd like**
Allow WithPrompt to be included in the URL produced by AuthURL() inside rp.AuthURLHandler()

**Describe alternatives you've considered**
New to the language but couldn't see an obvious way to inject the prompt AuthURLOpt into the authorization request

**Additional context**
None.

**Comment by fforootd** [comment]
@livio-a can you glance into this?

**Comment by livio-a** [comment]
Hey @shnplr 

I see the problem. The `AuthURLHandler` currently does not allow to do so.
It's only possible in the `AuthURL` function:
```
http.Redirect(w, r, rp.AuthURL(state, provider, rp.WithPrompt(oidc.PromptSelectAccount)), http.StatusFound)
```

I'll create a PR to change it and for the `CodeExchange` / `CodeExchangeHandler`.

**Comment by muhlemmer** [comment]
@livio-a 
If we expose `opts ...AuthURLOpt` in `AuthURLHandler()`, there will be a hypothetical case where a double code challenge can be set. 1 time by the caller using `WithCodeChallenge()` directly and 1 time by the conditional below:

https://github.com/zitadel/oidc/blob/fa222c5efb331a225c931b07721c33f55cf6c2bf/pkg/client/rp/relying_party.go#L345-L352

There is no way of knowing if it was already set in `opts`, as the `AuthURLOpt` type is a function, which cannot be compared to be equal in Go. Perhaps calling the option and comparing outputs or some other de-duplication logic when building the redirect URL, but that would be a dirty solution.

As `WithPrompt()` and `WithCodeChallenge()` are the only 2 `AuthURLOpt`s, I would propose to _only_ expose the ability of setting additional prompts:

```
func AuthURLHandler(stateFn func() string, rp RelyingParty, prompts ...string) http.HandlerFunc {
...
    if len(prompts) > 0 {
        opts = append(opts, WithPrompt(prompts...))
    }
...
}
```
> ... and for the `CodeExchange` / `CodeExchangeHandler`.

Likewise, for `CodeExchangeHandler()` there are only 2 `CodeExchangeOpt`s and both of them are set in conditionals. IMO we shouldn't change anything here:

https://github.com/zitadel/oidc/blob/fa222c5efb331a225c931b07721c33f55cf6c2bf/pkg/client/rp/relying_party.go#L415-L430

**Comment by muhlemmer** [comment]
Oops. I just now read #265, which would add more options. I will give it some more thought.

**Comment by muhlemmer** [comment]
I think I found a suitable solution. Perhaps we should continue the conversation at PR #273. Have a good weekend.
