### ISSUE TITLE
go run ... hangs indefinitely

### ISSUE THREAD

**Issue by prateekbansal** [zitadel/oidc#262]
**Describe the bug**
When I execute the command `go run github.com/zitadel/oidc/example/server`, the process seems to hang indefinitely. I don't see anything happening
```
$ go run github.com/zitadel/oidc/example/server
INFO[0000] signer exchanged signing key                  caller="/Users/pratikbansal/Downloads/zitadel/oidc/pkg/op/signer.go:83"
<hangs ...>
```

**To Reproduce**
1. Run the command `go run github.com/zitadel/oidc/example/server`

**Expected behavior**
The server should have started

**Desktop (please complete the following information):**
- OS: [e.g. iOS] MacOS
- Browser [e.g. chrome, safari] NA
- Version [e.g. 22] NA

**Comment by livio-a** [comment]
Hey @prateekbansal 

Thanks for the issue.

The command will indeed start the server as intended and will keep running until you stop it (CRTL + C).

I propose we update the README, stating that the client must be started in a separate terminal.
That command BTW will also start a listener, which has to be canceled.

Would that help?

**Comment by prateekbansal** [comment]
Hello @livio-a thx for your prompt response. I think for now even if I saw a message that "You server started at port ..." would be sufficient enough for me.

**Comment by livio-a** [comment]
@prateekbansal i've just created a PR solving this issue: #266
