### ISSUE TITLE
Device authorization grant

### ISSUE THREAD

**Issue by hifabienne** [zitadel/oidc#264]
As a developer I want to be able to use the device authorization grant for authentication, to be able to authenticate my devices.

**Acceptance Criteria**
- [x] I am able to authenticate with device authorization grant
- [x] Implementation follows the standard https://oauth.net/2/device-flow/
- [x] I am able to authenticate my device
- [x] I am able to use it in the OP
- [x] I am able to use it in the RP

**Additional Context**
Reported issue: #141

**Comment by muhlemmer** [comment]
I will read up on the RFC and give feedback in the discovery meeting Tuesday.
