### ISSUE TITLE
JWT access tokens for jwt profile

### ISSUE THREAD

**Issue by hifabienne** [zitadel/oidc#267]
As a developer I want to be able to receive a JWT access token when using JWT profile grant.

**Acceptance Criteria**
- [ ] I am able to define what kind of token I receive when using JWT profile

**Addtional Context**
- currently hard coded to CreateBearerToken
- needs TokenType (on RP we have Client interface for that)
- probably easiest way is to add an additional interface to return the type

**Comment by livio-a** [comment]
additional info:
- currently hard coded to `CreateBearerToken`
- needs TokenType (on RP we have Client interface for that)
- probably easiest way is to add an additional interface to return the type

**Comment by livio-a** [comment]
closed with https://github.com/zitadel/oidc/pull/271
