### ISSUE TITLE
How do I use an address other than localhost?  

### ISSUE THREAD

**Issue by njdan5691** [zitadel/oidc#268]
Sorry if this is documented somewhere already, but i didn't see it

**Comment by livio-a** [comment]
Hey @njdan5691 

Can you please give me some more information?
If you mean the server example, you would need to change the address, which is currently hardcoded:
https://github.com/zitadel/oidc/blob/main/example/server/main.go#L21

Just let me know what your use case is, so we can have a look at and check if we need to change something.

**Comment by hifabienne** [comment]
@njdan5691
Can you give some other information about your issue? Or could you already solve it?

**Comment by hifabienne** [comment]
@njdan5691 I will close this issue for now as it is not possible to us to help if we don't have some more information.
Feel free to reopen as soon as you can give us some more infos.
