### ISSUE TITLE
rp/mock: go generate fails

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/oidc#281]
When running `go generate ./...` on in the project root, it fails with:

```
prog.go:14:2: no required module provides package github.com/zitadel/oidc/pkg/rp; to add it:
        go get github.com/zitadel/oidc/pkg/rp
prog.go:12:2: no required module provides package github.com/golang/mock/mockgen/model: go.mod file not found in current directory or any parent directory; see 'go help modules'
prog.go:14:2: no required module provides package github.com/zitadel/oidc/pkg/rp: go.mod file not found in current directory or any parent directory; see 'go help modules'
2023/02/17 09:44:05 Loading input failed: exit status 1
generate.go:3: running "mockgen": exit status 1
```

https://github.com/zitadel/oidc/blob/c8d61c0858de6b503e38afd8798437b916044963/pkg/client/rp/mock/generate.go#L3

There are 2 issues here:

1. The path to the `rp` package has changed to `github.com/zitadel/oidc/pkg/client/rp`;
2. There is no type `Verifier` in neither the `client` or `rp` package;

Does somebody know what happened? What would be the correct type and package path?

**Comment by livio-a** [comment]
@muhlemmer i believe your on the next branch? i quickly had a look at the generator file and managed to run it with:
```go
//go:generate mockgen -package mock -destination ./verifier.mock.go github.com/zitadel/oidc/pkg/client/rp IDTokenVerifier
```

and as the next branch will be breaking we will need to change the module to v2 as well: `github.com/zitadel/oidc/v2`

**Comment by muhlemmer** [comment]
I couldn't find `rp.Verifier` on `main` neither. But if it's `IDTokenVerifier` it makes sense. The blame says that was changed 2 years ago :joy: . Do you even use the mocker anywhere?

Anyway, thanks for the hint and I'll send a quick fix to `next`.
