### ISSUE TITLE
Zitadel docs link broken

### ISSUE THREAD

**Issue by jame-developer** [zitadel/oidc#286]
**Broken link**
The link at https://github.com/zitadel/oidc/blob/main/README.md?plain=1#L81 is redirected to https://zitadel.com/docs/docs/guides/integrate/login-users, which does not exists

**To Reproduce**
1. Go to https://github.com/zitadel/oidc/blob/main/README.md#resources
2. Click on [OIDC/OAuth Flow in Zitadel (using this library)](https://docs.zitadel.com/docs/guides/integrate/login-users)

**Expected behavior**
The link leads to the correct page. I guess it should lead to https://zitadel.com/docs/guides/integrate/login-users

**Comment by muhlemmer** [comment]
Thanks for reporting this. We will fix the link

**Comment by jame-developer** [comment]
Great and thanks for fast response and fixing.
