### ISSUE TITLE
migrate from `gorilla/mux` to `go-chi/chi`

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/oidc#301]
See #300 for description.

## Acceptance criteria

- [x] all currently registered `gorilla/mux` routes replaced by `go-chi/chi`
- [x] regression all tests still passing without changes in execution
- [x] no `github.com/gorilla/mux` module in the `go.mod` remaining

**Comment by muhlemmer** [comment]
More or less ready for review, depending on other PR.
Time spend: approx 3 hours, including testing examples and troubleshooting #331.

@adlerhurst can I assign you for review once ready, since we talked about this migration on zitadel?

**Comment by jkroepke** [comment]
@muhlemmer Was there any reason, why the stdlib https://pkg.go.dev/net/http#NewServeMux is not sufficient here?

**Comment by muhlemmer** [comment]
Mainly we want to use the same router throughout our product, of which oidc is an essential part.
We had an open discussion about the subject here: https://github.com/zitadel/zitadel/issues/4285.

Yes, the `oidc/op` router could be done with `http.ServeMux`, but:
1. It misses the middleware functionality (`router.Use()`) and we would need to implement chaining ourselves.
2. The `example/server/exampleop` package use more specific functionalities like `router.Get()`, `router.Post()` and `router.Mount()`. As this would still pull in the module into the oidc project, so why not use it as the main router?

Are there any issues with `chi` which we are not aware of?

I would like to add that `op.Provider` now implements `http.Handler` directly so you can still use whatever router you seem fit for your own project.

**Comment by jkroepke** [comment]
> Are there any issues with chi which we are not aware of?

No. I just thought that external dependency that can avoid could be a benefit. Since zitadel/oidc has some security context, avoid unnecessary dependencies is always a archivable goal.

But It seems like chi has valid use-cases, that you explained well. 👍 

Thanks for the clarification!
