### ISSUE TITLE
feat: include TokenRequest in call to GetPrivateClaimsFromScopes

### ISSUE THREAD

**Issue by muir** [zitadel/oidc#323]
**Is your feature request related to a problem? Please describe.**

Right now, `GetPrivateClaimsFromScopes` does not have access to the token request.  This prevents it from adding a session id that ties the access token to the original request.   Without the tie to the original request, code must make assumptions about how the user authenticated and thus minor security vulnerabilities could be introduced.

**Describe the solution you'd like**

Change the API of `GetPrivateClaimsFromScopes`: simply add `TokenRequest` as another parameter.

**Describe alternatives you've considered**

Add a new API that is called after `GetPrivateClaimsFromScopes`: `GetPrivateClaimsFromRequest`.  That could be done in a backwards-compatible way by making the API optional.

**Comment by muhlemmer** [comment]
CC @livio-a , session management redesign?

**Comment by muir** [comment]
I just re-read `op.CreateIDToken`.   In it we have:

```go
        if okReq && okStorage {
                userInfo := new(oidc.UserInfo)
                err := teStorage.SetUserinfoFromTokenExchangeRequest(ctx, userInfo, tokenExchangeRequest)
                if err != nil {
                        return "", err
                }
                claims.SetUserInfo(userInfo)
        } else if len(scopes) > 0 {
                userInfo := new(oidc.UserInfo)
                err := storage.SetUserinfoFromScopes(ctx, userInfo, request.GetSubject(), request.GetClientID(), request, scopes)
                if err != nil {
                        return "", err
                }
                claims.SetUserInfo(userInfo)
        }
```

Right now, you can either have scopes or the request.  There is no code path that gives you both.  Scopes can be obtained from the request going down the `SetUserinfoFromTokenExchangeRequest` path, but those scopes aren't the raw scopes from the request.  They've been modified a couple of different ways.

I want to combine the `SetUserinfoFromTokenExchangeRequest` and `SetUserinfoFromScopes` calls: I want both the request and the scopes available at the same time.   The most minimal changes, from my point-of-view, would be adding `scopes` to the `GetPrivateClaimsFromTokenExchangeRequest` call and/or adding `request` to the `SetUserinfoFromScopes` call.

@muhlemmer : have we frozen the 2.0 API, or are we still open to breaking changes?

Related, but separately, the `op.TokenExchangeStorage` interface needs documentation.  It's an optional interface but there is no discussion of why it should be implemented.

**Comment by muhlemmer** [comment]
2.0 is frozen. `next` is open for v3. We will probably not stay on v2 very long.  I'm discussing your proposals with the team this afternoon.

**Comment by muhlemmer** [comment]
> Related, but separately, the op.TokenExchangeStorage interface needs documentation. It's an optional interface but there is no discussion of why it should be implemented.

It implements [RFC 9693](https://www.rfc-editor.org/rfc/rfc8693.html), it was introduced by a community PR #255

**Comment by muhlemmer** [comment]
> Change the API of `GetPrivateClaimsFromScopes`: simply add TokenRequest as another parameter.

We wouldn't mind if `GetPrivateClaimsFromScopes` is modified to the following: Pass the whole `TokenRequest` instead of the subject. As Subject is already taken from the `TokenRequest`. On our side it wouldn't break much, as we just need to call the `GetSubject()` method on the request instead.

```go
GetPrivateClaimsFromScopes(ctx context.Context, req TokenRequest, clientID string, scopes []string) (map[string]interface{}, error)
```

> adding scopes to the `GetPrivateClaimsFromTokenExchangeRequest`

Don't you mean `SetPrivateClaimsFromTokenExchangeRequest`?

> adding request to the `SetUserinfoFromScopes` call.

Like above, we can replace `userID` and `clientID` with the `IDTokenRequest` and get those IDs inside the implementation.

```go
SetUserinfoFromScopes(ctx context.Context, userinfo *oidc.UserInfo, req IDTokenRequest, scopes []string) error
```

**Comment by muir** [comment]
In #347, I deprecate `op.SetUserinfoFromScopes` in favor of `op.SetUserinfoFromRequest`.
In `next`, `op.CanSetUserinfoFromRequest` (added) should be removed.

Implementers can switch to `op.SetUserinfoFromRequest` immediately and have an empty 
implementation of `op.SetUserinfoFromScopes`. To get the subject and client 
(current parameters to `op.SetUserinfoFromScopes`) in `op.SetUserinfoFromRequest`,
call `token.GetSubject()` and `request.GetClientID` respectively.

**Comment by muir** [comment]
@muhlemmer I think this can be closed.  Close it?
