### ISSUE TITLE
feat: provide the request info in Context for all Storage() callbacks

### ISSUE THREAD

**Issue by muir** [zitadel/oidc#325]
**Is your feature request related to a problem? Please describe.**

Several times I've needed information that is present in the original `http.Request` when implementing `op.Storage` APIs or even `Client` APIS.

**Describe the solution you'd like**

Capture the original `http.Request` and request body and put them into `context.Context` so any `op.Storage` API can get that information if it needs it.

**Describe alternatives you've considered**

Change all of the `op.Storage` APIs to include additional information.

**Comment by muhlemmer** [comment]
I'm not sure if we would want something like this, so I will take it up with my colleagues. Meanwhile. you could easily achieve this by creating your own middleware:

```
type ReqKeyT int

const ReqKey ReqKeyT = 0

func requestToCtx(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := context.WithValue(r.Context(), ReqKey, r)
		next.ServeHTTP(w, r.WithContext(ctx))
	})
}
```

```
	handler, err := op.NewOpenIDProvider(issuer, config, storage,
		//we must explicitly allow the use of the http issuer
		op.WithAllowInsecure(),
		// as an example on how to customize an endpoint this will change the authorization_endpoint from /authorize to /auth
		op.WithCustomAuthEndpoint(op.NewEndpoint("auth")),
		op.WithHttpInterceptors(requestToCtx),
	)
```

**Comment by muhlemmer** [comment]
Closing as this is the alternative solution to #326. Also discussed in discord.

**Comment by muir** [comment]
@muhlemmer  There are other situations where the entire request is useful.  In my implementation, I'm passing the request through to the storage layer (using Context)  for `/authorize`, `/revoke`, and `/end_session`.  We can solve those individually, but it seems like a general solution is warranted.
