### ISSUE TITLE
Example app flow doesn't work on Chrome-111

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/oidc#331]
**Describe the bug**

It appears that Google Chrome is not allowing the secure cookie to be set on localhost.

**To Reproduce**
1.  Terminal 1, run: `go run ./example/server`
2. Terminal 2, run `CLIENT_ID=web CLIENT_SECRET=secret ISSUER=http://localhost:9998/ SCOPES="openid profile" PORT=9999 go run ./example/client/app`
3. Open Chrome and browser to http://127.0.0.1:9999/login
4. You get redirected to login page. Enter credentials: `test-user@localhost` / `verysecure` and click "login"
5. After redirect to callback URL, the following message is in the browser window: `failed to get state: http: named cookie not present`

**Expected behavior**

User info to be printed like:

```
{"family_name":"User","given_name":"Test","locale":"de","name":"Test User","preferred_username":"test-user@localhost","sub":"id1"}
```

**Screenshots**

![image](https://user-images.githubusercontent.com/5411563/225436087-90f358d1-9c86-4855-8425-bd8df607e468.png)

Error message and no cookies set for this domain

**Desktop (please complete the following information):**
- OS: 6.1.12-gentoo-dist AuthenticAMD GNU/Linux with KDE Plasma 5.26.5
- Browser: Google Chrome
- Version 111.0.5563.64 (Official Build) (64-bit)

**Additional context**

Works fine in Firefox-111:

![image](https://user-images.githubusercontent.com/5411563/225437239-61d464f6-4ce7-4eaf-a49d-dbd00711ea2c.png)

**Comment by xrstf** [comment]
I think this might be because you, like me, started the server with localhost:9999, but then used 127.0.0.1:9999 in Chrome, yet localhost:9999 in Firefox.

When consistently using "localhost", I at least do not get the `named cookie not present` error anymore.

**Comment by muhlemmer** [comment]
Thanks for the feedback! you are right. Closing this.
