### ISSUE TITLE
Implement Client Credentials (client)

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [zitadel/oidc#350]
**Is your feature request related to a problem? Please describe.**
Sadly there is no support for Client Credentials (rp).
So instead of having a semantic example, I have to do http requests manually.

**Comment by muhlemmer** [comment]
You can already specify client credentials in [`rp.NewRelyingPartyOIDC()`](https://pkg.go.dev/github.com/zitadel/oidc/pkg/client/rp#NewRelyingPartyOIDC), use the [`WithClientKey()`](https://pkg.go.dev/github.com/zitadel/oidc/v2/pkg/client/rp#WithClientKey) or  [`WithJWTProfile()`](https://pkg.go.dev/github.com/zitadel/oidc/v2/pkg/client/rp#WithJWTProfile) Options.

If there is something we are missing, can you please provide more details where we should add Client Credentials support.

**Comment by muhlemmer** [comment]
closing this issue. please let us know if there is still an issue.
