### ISSUE TITLE
Device authorization flow fails on polling after first try

### ISSUE THREAD

**Issue by monstermunchkin** [zitadel/oidc#352]
**Describe the bug**
When using device authorization flow, polling for the access token fails after the first try with
```
ErrorType=unauthorized_client Description=Grant type 'urn:ietf:params:oauth:grant-type:device_code,urn:ietf:params:oauth:grant-type:device_code' not allowed for the client.
```

That is because `grant_type` contains the `urn:ietf:params:oauth:grant-type:device_code` value twice instead of once. I believe this is caused by the `client.DeviceAccessTokenRequest` struct containing the grant type twice, once in `oidc.ClientCredentialsRequest`, and again in `oidc.DeviceAccessTokenRequest`:

```go
type DeviceAccessTokenRequest struct {
	*oidc.ClientCredentialsRequest
	oidc.DeviceAccessTokenRequest
}
```

This should somehow be deduplicated.

**To Reproduce**
1. Try using the device authorization flow
2. See error: ```ErrorType=unauthorized_client Description=Grant type 'urn:ietf:params:oauth:grant-type:device_code,urn:ietf:params:oauth:grant-type:device_code' not allowed for the client.```

**Expected behavior**
Polling should work correctly, instead of failing straight away.

**Comment by muhlemmer** [comment]
I understand the issue. However, when I run the example and debug the raw request, the request body looks like this:

```
client_assertion=&client_assertion_type=&client_id=web&client_secret=secret&device_code=bUvevBowW8iCpNKovWtiqw&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&scope=
```

Yes, the `grant_type` is specified twice. But that should not decode into a single comma-separated string by the receiver, but an array or slice. For example, Go's `r.ParseForm()` decodes in `url.Values` / `map[string][]string`. And `Get()`ing a value by key still returns the value once. So you might have a bug in whatever server your are running, as well. (Running it against our own example `op` works just fine)

That being said, it should be an easy fix. It seems I'm setting the `grant_type` twice when building the request:

https://github.com/zitadel/oidc/blob/e1d50faf9b58798a0b4e397fea37a93a464ac5ba/pkg/client/rp/device.go#L51
https://github.com/zitadel/oidc/blob/e1d50faf9b58798a0b4e397fea37a93a464ac5ba/pkg/client/rp/device.go#L15

We can delete the latter and it should be fine.

**Comment by monstermunchkin** [comment]
> I understand the issue. However, when I run the example and debug the raw request, the request body looks like this:

Same here. But both Keycloak and Auth0 don't like the duplicate parameter. With Keycloak I get:
```
ErrorType=invalid_request Description=duplicated parameter
```

**Comment by muhlemmer** [comment]
If you want, you can send a PR that deletes this line:

https://github.com/zitadel/oidc/blob/e1d50faf9b58798a0b4e397fea37a93a464ac5ba/pkg/client/rp/device.go#L15

Otherwise, I'll take care of it in the next few days.
