### ISSUE TITLE
acr_values should be a space separated string

### ISSUE THREAD

**Issue by dellekappa** [zitadel/oidc#376]
As defined in  https://openid.net/specs/openid-connect-core-1_0.html#AuthRequest, the `acr_values` parameter should be handled as a space-separeted string.

Actually is defined as 
```golang
ACRValues    []string            `json:"acr_values" schema:"acr_values"`
```

instead of
```golang
ACRValues   SpaceDelimitedArray  `json:"acr_values" schema:"acr_values"`
```

This causes a panic when a request object of this kind is used:

```json
{
  ...
  "acr_values": "foo-bar"
}
```

**Comment by hifabienne** [comment]
@dellekappa thanks for the report we will have a look at it

**Comment by muhlemmer** [comment]
@dellekappa you are right. This can be considered a bug.

If you want, you can open a PR with a fix against the `next` branch, just to make sure it doesn't break for people that depend on the current but broken implementation. If you are not able, we will pick it up but it might take a bit longer ;).
