### ISSUE TITLE
deprecated: square/go-jose

### ISSUE THREAD

**Issue by FerdinandvHagen** [zitadel/oidc#390]
**Is your feature request related to a problem? Please describe.**
The used jwt module https://github.com/square/go-jose is deprecated as of february of this year (latest) and no longer maintained.
A new version has been published to a dedicated organization: https://github.com/go-jose/go-jose

**Describe the solution you'd like**
Upgrade to a maintained module.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by muhlemmer** [comment]
Thanks for pointing out the issue. We are aware of the situation and are discussing / looking out for a suitable replacement.

Unfortunately go-jose/jose doesn't look too well either. The new maintainer already noted that he is not able to maintain the lib very well, open issues/PRs are not handelend in a timely matter. And there seem to be some breaking changes in v3 that some users complained about. Therefore we are hesitant to make the switch anytime soon.

Other suggestions are welcome.

**Comment by arianvp** [comment]
https://github.com/lestrrat-go/jwx is well-maintained and featureful

**Comment by dechristopher** [comment]
We'd love to see the adoption of go-jose/v3 as well. It's painful to need to use both v2 and v3 in our environment just to use Zitadel OIDC.

**Comment by muhlemmer** [comment]
> We'd love to see the adoption of go-jose/v3 as well. It's painful to need to use both v2 and v3 in our environment just to use Zitadel OIDC.

What is your experience so far with the new v3? Did the breaking changes cause any big issues? Would you consider it stable enough?

**Comment by mateuszmidor** [comment]
Totally; go-jose/v3 is of top importance as we deal with security here.

**Comment by muhlemmer** [comment]
I've opened a PR for the `next` branch. This should become part of our v3 release, which I intend to do in the next week(s)
