### ISSUE TITLE
Is there any way to use a custom validator?

### ISSUE THREAD

**Issue by anderspitman** [zitadel/oidc#393]
I'm trying to implement a simple OIDC server that uses the "registration-free" OAuth2 setup described here:

https://aaronparecki.com/2018/07/07/7/oauth-for-the-open-web

Essentially instead of needing to register a client with the OP ahead of time, the OP simply verifies at auth request time that the redirect URL is on the same domain as the client_id (which is simply the URL where the client app is hosted).

After some poking through the code, `zitadel/oidc` appears to be hard-coded to only allow pre-registered clients.

[This line](https://github.com/zitadel/oidc/blob/8d0819ee8ac9fa537b6b3b417118cc8dd99608d9/pkg/op/auth_request.go#L92) seems to indicate that it's possible to override the validation, but I don't see how to do that without modifying `op.Provider`. Am I missing something?

**Comment by anderspitman** [comment]
Thanks for the response. I think that would work, but would force the client_id URL to exactly match the redirect_uri. It would be ideal if the constraint was somewhat looser. For example, client_id=example.com and redirect_uri=https://example.com/oauth. For security purposes you can still verify that client_id is a prefix of redirect_uri, but you also get flexibility in implementing the URLs.

**Comment by muhlemmer** [comment]
As we now have a the new server interface, this allows you to implement the OP however you want. We now also have wildcard support. Will now close this issue as we do not intend to change more in this regard.
