### ISSUE TITLE
AuthCallbackURL removes issuer path prefix

### ISSUE THREAD

**Issue by danicc097** [zitadel/oidc#408]
Using v2.6.3 example server as reference. It seems like `AuthCallbackURL` returns the callback path without issuer prefix, e.g. `https://authserver.dev.localhost/oidc` -> `https://authserver.dev.localhost/auth/callback?id=dd882928-712f-480f-a9f8-33c15adaa1a8`, expected correct `https://authserver.dev.localhost/oidc/auth/callback?id=dd882928-712f-480f-a9f8-33c15adaa1a8`. 
I rolled back to `http.Redirect(w, r, prefix+"/auth/callback?id="+id, http.StatusFound)` as workaround as in v1.

**Comment by muhlemmer** [comment]
I can confirm the issue and we will work an a fix.

**Comment by muhlemmer** [comment]
The bug was in the example itself. Please see the linked PR for details.
