### ISSUE TITLE
client/rs: error when issuer discovery has no introspection endpoint

### ISSUE THREAD

**Issue by hhromic** [zitadel/oidc#413]
**Describe the bug**
When an issuer does not provide an introspection endpoint during discovery, `newResourceServer()` fails with:
```
introspectURL and/or tokenURL is empty: please provide with either `WithStaticEndpoints` or a discovery url
```
Note that a token endpoint is always provided by the issuer.

According to the OpenID specs for [Discovery responses](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse), an introspection endpoint is not mandatory (not defined in the response object) while the token endpoint is required.

Three examples of issuers that do not provide any introspection endpoint are:
* Google: <https://accounts.google.com/.well-known/openid-configuration>
* Spotify: <https://accounts.spotify.com/.well-known/openid-configuration>
* PayPal: <https://www.paypal.com/.well-known/openid-configuration>

This is because of the following (incorrect) check after discovery that assumes that both endpoints must be present:
https://github.com/zitadel/oidc/blob/9e624986aaf6eb8854ffc4702d7d1cc755919ff5/pkg/client/rs/resource_server.go#L83-L85

In reality, the introspection endpoint is valid to be empty.

**To Reproduce**
Consider the following demonstration Go program:
```go
package main

import (
	"fmt"

	"github.com/zitadel/oidc/v2/pkg/client/rs"
)

const (
	Issuer = "https://accounts.google.com"
//	Issuer = "https://accounts.spotify.com"
//	Issuer = "https://www.paypal.com"
	ClientId = "client-id"
	ClientSecret = "client-secret"
)

func main() {
	rscc, err := rs.NewResourceServerClientCredentials(
		Issuer,
		ClientId,
		ClientSecret,
	)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%+v\n", rscc)

	res, err := rs.Introspect(nil, rscc, "test-token")
	if err != nil {
		panic(err)
	}

	fmt.Printf("%+v\n", res)
}
```
When running the above program, an panic is emitted after the error from `NewResourceServerClientCredentials()`:
```
$ go run main.go
panic: introspectURL and/or tokenURL is empty: please provide with either `WithStaticEndpoints` or a discovery url

exit status 2
```

**Expected behavior**
Given that in the demonstration program above I'm using the discovery mechanism, I expect it to not fail when the issuer does not provide an introspection endpoint during discovery as it is an optional feature.

Instead, I expect the `rscc` object to be correctly instantiated and a future call to `rs.Introspect()` fails with an error related to the introspection endpoint not being set. This would allow to still use `rscc` (for the authorizer functionality) but without introspection support.

It can be argued that if an issuer is known to not provide an introspection endpoint, it can be given statically using `WithStaticEndpoints("", "https://some.host/introspection-endpoint")` (or a dummy value) but is highly unlikely that a provider has a manual introspection endpoint and does not provide it in discovery. This would just propagate a confusing error later during `rs.Introspect()`.

**Potential Solution**
I propose to instead accept that discovery may not provide an introspection endpoint, do not fail in this situation, and add a check for an empty introspection endpoint in `rs.Introspect()` to clearly indicate that the issuer does not support introspection.

In addition, discovery should only set `introspectURL` or `tokenURL` if they were not given in static endpoint arguments.

If the above makes sense, I already have this logic implemented here:
https://github.com/hhromic/oidc/compare/main...hhromic:oidc:fix-rs-discovery

As it can be seen, I also made a set of unit tests that cover this issue.
Let me know if you agree with the above proposal to open a PR with these changes.

**Comment by muhlemmer** [comment]
Thanks for the very detailed bug report and proposed fix!

> According to the OpenID specs for [Discovery responses](https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationResponse), an introspection endpoint is not mandatory (not defined in the response object) while the token endpoint is required.

I verified this and I agree.

Please submit you patch as a PR and we will review it. Tomorrow we have a bug-fix session, so if we get it on time I will take care of the review then.

**Comment by hhromic** [comment]
> Please submit you patch as a PR and we will review it. Tomorrow we have a bug-fix session, so if we get it on time I will take care of the review then.

Great to see such a quick reply! Happy to help contributing to this nice project.
I sent a PR now from the branch I made with the fixes and unit tests. Looking forward for reviewing 👍
