### ISSUE TITLE
state always returned in access token response

### ISSUE THREAD

**Issue by livio-a** [zitadel/oidc#446]
A customer reported that the state is returned in the code flow, which causes an issue with his library.

OAuth2 and OIDC 1.0 define that a `state` must be present in the Access Token Response for the Implicit Flow.
We currently also return that in the Code Flow, which does not follow the spec (and does not make sense as the state is used for the state transfer of the user agent flow).

**Comment by muhlemmer** [comment]
State has `omitempty` flag. The value is taken from the AuthReques. Meaning, if the auth request doesn't have it, it will not be part of the token response.

https://github.com/zitadel/oidc/blob/976b40620c782ea49b88a0274f8a9c375a5727cf/pkg/oidc/token.go#L207-L214

https://github.com/zitadel/oidc/blob/976b40620c782ea49b88a0274f8a9c375a5727cf/pkg/op/token.go#L54

State isn't something we generate, but we receive it from the client in the `Authorize` handler:

https://github.com/zitadel/oidc/blob/976b40620c782ea49b88a0274f8a9c375a5727cf/pkg/op/auth_request.go#L69-L74

https://github.com/zitadel/oidc/blob/976b40620c782ea49b88a0274f8a9c375a5727cf/pkg/oidc/authorization.go#L66-L91

The way I see it, we only return `state` if it was supplied by the client first. If the client breaks on that, it shouldn't include `state` in the authentication request.

**Comment by ldabrowskiairspan** [comment]
This bug is back in versions 2.53.x and newer:
![image](https://github.com/zitadel/oidc/assets/112943570/299f1fb0-f1d0-4d16-9700-f05642eb76a3)
![image](https://github.com/zitadel/oidc/assets/112943570/ad50aaf1-303f-40cb-84a8-de52a6d5a480)

**Comment by muhlemmer** [comment]
@ldabrowskiairspan some of the logic has moved to zitadel recently. Can you please file a [bug report](https://github.com/zitadel/zitadel/issues/new?assignees=&labels=bug&projects=&template=BUG_REPORT.yaml&title=%5BBug%5D%3A+) there so we can track it?

**Comment by ldabrowskiairspan** [comment]
@muhlemmer Opened here: https://github.com/zitadel/zitadel/issues/8110
