### ISSUE TITLE
PKCE support is not enough

### ISSUE THREAD

**Issue by ay4toh5i** [zitadel/oidc#471]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Thanks such a nice library!

I notice that pkce is verified only when the auth method is none in code exchenge.
https://github.com/zitadel/oidc/blob/d58ab6a11584cf458cde09643588b2abeb7c5221/pkg/op/token_code.go#L96-L103

However, pkce should be verified in other methods to mitigate vulnerabilities as decribed below.

> PKCE is not a form of client authentication, and PKCE is not a replacement for a client secret or other [client authentication](https://oauth.net/2/client-authentication/). PKCE is recommended even if a client is using a client secret or other form of client authentication like private_key_jwt.

https://oauth.net/2/pkce/

### Describe your ideal solution

If pkce params requested in authorize, verifying that as possible is ideal.

### Environment

Self-hosted

**Comment by muhlemmer** [comment]
Although I agree with the recommendation, oauth.net is not a definitive resource for the standard, which is described in RFCs. What you describe is Oauth V2.1 I believe. We already have an issue open for that: https://github.com/zitadel/oidc/issues/254. You can vote there with a thumbs up and we can assign priorities based on that.

At the moment we are compliant with Oauth V2. Closing as duplicate.
