### ISSUE TITLE
Switch to `log/slog`

### ISSUE THREAD

**Issue by jkroepke** [zitadel/oidc#549]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

While `log/slog` and `golang.org/x/exp/slog` having the same API, they could not used together.

According to the README, if `zitadel/oidc` switches to go 1.22, it should be safe to use `log/slog`, since it's supported since go 1.21.

### Describe your ideal solution

I'm able to pass the `log/slog` logger to `zitadel/oidc` library calls.

### Version

3.12.0

### Environment

Self-hosted

**Comment by muhlemmer** [comment]
I had some issues installing go 1.22 on my system, but managed Friday. I will do the version bumping stuff after the weekend, along with the move to log/slog
