### ISSUE TITLE
[Bug]: The behavior of response_mode does not adhere to the guidelines

### ISSUE THREAD

**Issue by ay4toh5i** [zitadel/oidc#550]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the problem caused by this bug

Please check the [OAuth 2.0 Multiple Response Type Encoding Practices](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html)

> 7.  Security Considerations
There are security implications to encoding response values in the query string. The HTTP Referer header includes query parameters, and so any values encoded in query parameters will leak to third parties. Thus, while it is safe to encode an Authorization Code as a query parameter when using a Confidential Client (because it can't be used without the Client Secret, which third parties won't have), more sensitive information such as Access Tokens and ID Tokens MUST NOT be encoded in the query string. In no case should a set of Authorization Response parameters whose default Response Mode is the fragment encoding be encoded using the query encoding.

As per the document, it is imperative that sensitive information like Access Tokens and ID Tokens are not encoded in the query string. However, the current library implementation encodes all parameters in the query string.

### To reproduce

Please see below code.
https://github.com/zitadel/oidc/blob/f4bbffb51b60be934f1b79082de71d8aba4f6eaf/pkg/op/auth_request.go#L524-L526

https://github.com/zitadel/oidc/blob/f4bbffb51b60be934f1b79082de71d8aba4f6eaf/pkg/op/auth_request.go#L543-L552

### Expected behavior

The use of response_mode=query is practically only permissible when response_type=code or response_type=none is specified.
So the validation is required during the authorization request, I think.

**Comment by muhlemmer** [comment]
@ay4toh5i I don't understand why you are opening a bug if there is already a feature request #515 which you are clearly aware of? From our point of view, if a new guideline or standard is published, the implementation of such standard is a feature or enhancement, not a bug.

We maintain a list features in the [https://github.com/zitadel/oidc/blob/main/README.md#features](Readme). Only if we misbehave with regards to the mentioned standards, we consider that a bug.

We do appreciate the PR which you send, I will have a look at it shortly.

**Comment by ay4toh5i** [comment]
@muhlemmer 
This issue concerns the behavior of the `response_mode` being not `form_post`.
The specification [OpenID Connect Core 1.0(2014)](https://openid.net/specs/openid-connect-core-1_0-final.html#AuthRequest) includes the `response_mode` parameter and it refers to [OAuth 2.0 Multiple Response Type Encoding Practices(2014)
](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html)
So this specification is not a new standard, but is already included `OpenID Connect Core 1.0`.

That document states that under no circumstances should a set of Authorization Response parameters, whose default Response Mode is the fragment encoding, be encoded using the query encoding.

As you mentioned, `zitadel/oidc` should implement `OpenID Connect Core 1.0 implicit flow`.
Therefore, I believe this behavior constitutes a bug.
