### ISSUE TITLE
Set IDTokenSigningAlgValuesSupported of DiscoveryConfiguration obtained by Discover when initializing RelyingParty.

### ISSUE THREAD

**Issue by otakakot** [zitadel/oidc#574]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

When [IDTokenVerifier](https://github.com/zitadel/oidc/blob/v3.18.0/pkg/client/rp/relying_party.go#L68) is executed on a RelyingParty created with [NewRelyingPartyOIDC](https://github.com/zitadel/oidc/blob/v3.18.0/pkg/client/rp/relying_party.go#L217), only RS256 is supported.

[CheckSignature](https://github.com/zitadel/oidc/blob/main/pkg/oidc/verifier.go#L150) is performed on [VerifyIDToken](https://github.com/zitadel/oidc/blob/v3.18.0/pkg/client/rp/verifier.go#L33), but only RS256 is supported because supportedSigAlgs is always set to 0.

To solve this, specify [WithSupportedSigningAlgorithms](https://github.com/zitadel/oidc/blob/v3.18.0/pkg/client/rp/verifier.go#L168) in the options argument of NewRelyingPartyOIDC.

To determine the value of WithSupportedSigningAlgorithms, create a [DiscoveryConfiguration](https://github.com/zitadel/oidc/blob/v3.18.0/pkg/oidc/discovery.go#L7) using the [Discover](https://github.com/zitadel/oidc/blob/v3.18.0/pkg/client/client.go#L30) method and specify IDTokenSigningAlgValuesSupported.

It is inefficient to use the Discover method twice with NewRelyingPartyOIDC and WithSupportedSigningAlgorithms.

### Describe your ideal solution

Add the following processing in [NewRelyingPartyOIDC](https://github.com/zitadel/oidc/blob/v3.18.0/pkg/client/rp/relying_party.go#L217).

```go
	rp.verifierOpts = append(rp.verifierOpts, WithSupportedSigningAlgorithms(discoveryConfiguration.IDTokenSigningAlgValuesSupported...))

```

### Version

v3.18.0

**Comment by muhlemmer** [comment]
Similar to https://github.com/zitadel/oidc/issues/506 where duplicate calls are used for obtaining and setting PKCE config. I would want to propose a configuration option for the RP which will let it take the signing algorithms from the discovery call.

```go
// WithSigningAlgsFromDiscovery appends the [WithSupportedSigningAlgorithms] option to the Verifier Options.
// The algorithms returned in the `id_token_signing_alg_values_supported` from the discovery response will be set.
func WithSigningAlgsFromDiscovery()
```

We are open for a PR.

**Comment by otakakot** [comment]
@muhlemmer 

Thank you for your comment.
My revised proposal did not maintain public relations compatibility.
I will consider PR based on your revised proposal.
