### ISSUE TITLE
Mark pkg.strings for deprecation

### ISSUE THREAD

**Issue by isegura-eos-eng** [zitadel/oidc#679]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Since go1.21 there exist a stdlib `slices` package. This includes the functionality that this project `pkg/strings`, which is the `strings.Contains` function. The homonymous `slices` function works also for strings.

### Describe your ideal solution

I propose to mark this function for deprecation and remove any reference from the project code. This way package clients can still use this for v3.

### Version

3.33.1

### Environment

Self-hosted

### Additional Context

I'm gonna submit the PR, we already discussed this briefly in: https://github.com/zitadel/oidc/issues/660#issuecomment-2402050196

**Comment by hifabienne** [comment]
I think we can close this issue as the pr is already mergedd
